Warning: There were 7484 divergent transitions after warmup. See
https://mc-stan.org/misc/warnings.html#divergent-transitions-after-warmup to
find out why this is a problem and how to eliminate them.

Warning: There were 1188 transitions after warmup that exceeded the maximum
treedepth. Increase max_treedepth above 10. See
https://mc-stan.org/misc/warnings.html#maximum-treedepth-exceeded

Warning: Examine the pairs() plot to diagnose sampling problems

Warning: The largest R-hat is 1.08, indicating chains have not mixed. Running
the chains for more iterations may help. See
https://mc-stan.org/misc/warnings.html#r-hat

Warning: Bulk Effective Samples Size (ESS) is too low, indicating posterior
means and medians may be unreliable. Running the chains for more iterations may
help. See https://mc-stan.org/misc/warnings.html#bulk-ess

Warning: Tail Effective Samples Size (ESS) is too low, indicating posterior
variances and tail quantiles may be unreliable. Running the chains for more
iterations may help. See https://mc-stan.org/misc/warnings.html#tail-ess

